version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: 'host'
    #ports:
    #  - '53:53/tcp'
    #  - '53:53/udp'
    #  - '67:67/tcp'
    #  - '67:67/udp'
    #  - '1026:80/tcp'
    environment:
      WEBUIBOXEDLAYOUT: 'traditional'
      WEBTHEME: 'default-darker'
      TZ: 'America/New_York'
      WEB_PORT: '1026'
      WEBPASSWORD: 'pihole'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
      DNSMASQ_LISTENING: 'local'
      DHCP_ACTIVE: 'true'
      DHCP_START: '192.168.2.10'
      DHCP_END: '192.168.2.254'
      DHCP_ROUTER: '192.168.2.1'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
